# hmaarrfk 2022/07
# it seems that wxWidgets requires at least 10.11
# But mesalib requires 10.12
# https://github.com/conda-forge/mesalib-feedstock/blob/main/recipe/conda_build_config.yaml
c_stdlib_version:          # [osx and x86_64]
  - "11.0"                 # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "11.0"                 # [osx and x86_64]
