{% set version = "3.1.4" %}
{% set major_minor_version = '.'.join(version.split('.')[:2]) %}

package:
  name: wxwidgets
  version: {{ version }}

source:
  url: https://github.com/wxWidgets/wxWidgets/releases/download/v{{ version }}/wxWidgets-{{ version }}.tar.bz2
  sha256: 3ca3a19a14b407d0cdda507a7930c2e84ae1c8e74f946e0144d2fa7d881f1a94

build:
  number: 0
  run_exports:
    # ABI seems to be stable between minor versions
    - {{ pin_subpackage('wxwidgets', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake        # [win]
    - ninja        # [win]
    - make         # [unix]
    - pkg-config   # [unix]

    # Necessary CDTs
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxinerama-devel') }}     # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libxxf86vm-devel') }}      # [linux]

  host:
    - zlib
    - libpng
    - libtiff
    - expat
    - jpeg
    - libiconv    # [unix]
    - xz          # [unix]
    - glib        # [unix]
    - pango       # [unix]
    - cairo       # [unix]
    - fontconfig  # [unix]
    - gdk-pixbuf  # [unix]
    - gtk3        # [linux]
    - libglu       # [linux]
    - mesalib      # [unix]
    - xorg-libx11  # [linux]
    - xorg-libsm   # [linux]
    - xorg-libxi   # [linux]
  run:
    - fontconfig
    - pango
    - gtk3         # [linux]
    - xorg-libx11  # [linux]
    - xorg-libsm   # [linux]
  run_constrained:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]

test:
  commands:
    - test -f ${PREFIX}/lib/libwx_baseu-{{ major_minor_version }}${SHLIB_EXT}  # [unix]
    - test -f ${PREFIX}/include/wx-{{ major_minor_version }}/wx/wx.h           # [unix]
    - wx-config --prefix  # [unix]
    - wxrc --help  # [unix]
    - where wxrc   # [win]
    - if not exist %LIBRARY_BIN%\\wxrc.exe exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\wxmsw313u_xrc_vc_x64_custom.dll exit 1  # [win]


about:
  home: https://www.wxwidgets.org/
  license: Other
  license_family: LGPL
  license_file:
    - docs/licence.txt
    - docs/lgpl.txt
    - docs/gpl.txt
  summary: Cross-Platform GUI Library

  description: |
    wxWidgets is a C++ library that lets developers create applications for
    Windows, macOS, Linux and other platforms with a single code base. It has
    popular language bindings for Python, Perl, Ruby and many other languages,
    and unlike other cross-platform toolkits, wxWidgets gives applications a
    truly native look and feel because it uses the platform's native API rather
    than emulating the GUI. It's also extensive, free, open-source and mature.
  doc_url: https://docs.wxwidgets.org/
  dev_url: https://github.com/wxWidgets/wxWidgets/

extra:
  recipe-maintainers:
    - hmaarrfk