{% set version = "3.3.1" %}
{% set major_minor_version = '.'.join(version.split('.')[:2]) %}

package:
  name: wxwidgets
  version: {{ version }}

source:
  url: https://github.com/wxWidgets/wxWidgets/releases/download/v{{ version }}/wxWidgets-{{ version }}.tar.bz2
  sha256: f936c8d694f9c49a367a376f99c751467150a4ed7cbf8f4723ef19b2d2d9998d
  patches:
    # Without this patch, the cross compiled libraries get a host_suffix
    # which we do not want for conda-forge packages
    - 0001-Remove-host-prefix-suffix-when-cross-compiling.patch
    # Work-around issue in cmake config - should be
    # removed in wxwidgets 3.3.2
    # (https://github.com/wxWidgets/wxWidgets/pull/25655)
    - 0002-win32-msvc-naming.patch

build:
  number: 3
  run_exports:
    # upstreams seems to intend to keep a stable ABI, but we note
    # https://github.com/wxWidgets/wxWidgets/issues/25173 revealed
    # 3.2.6 broke the ABI, and it is unclear what will be done in
    # the future, so let's preemptively guard against breakage
    - {{ pin_subpackage('wxwidgets', max_pin='x.x.x') }}
  skip_compile_pyc:
    - "*.py"

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake        # [win]
    - ninja        # [win]
    - make         # [unix]
    - pkg-config   # [unix]

  host:
    - zlib
    - libpng
    - libtiff
    - expat
    # hmaarrfk 2020/05/25
    # Even after we specify that we want to use sys libjpeg-turbo
    # conda claims we are still overlinking on windows
    # not too sure why
    - libjpeg-turbo
    - pcre2
    - liblzma-devel
    - libiconv                          # [unix]
    - libcurl                           # [unix]
    - glib                              # [linux]
    - pango                             # [linux]
    - cairo                             # [linux]
    - fontconfig                        # [linux]
    - gdk-pixbuf                        # [linux]
    - gtk3                              # [linux]
    - libglu                            # [linux]
    - gst-plugins-base {{ gstreamer }}  # [linux]
    - gstreamer                         # [linux]
    - libgl-devel                       # [linux]
    - libglx-devel                      # [linux]
    - xorg-libx11                       # [linux]
    - xorg-libsm                        # [linux]
    - xorg-libxi                        # [linux]
    - xorg-libxxf86vm                   # [linux]
    - xorg-libxrandr                    # [linux]
    - xorg-libxinerama                  # [linux]
    - xorg-libxdamage                   # [linux]
    - xorg-libxcomposite                # [linux]
    - xorg-libxcursor                   # [linux]
    - xorg-libxtst                      # [linux]
    - xorg-xorgproto                    # [linux]
  run:
    - xorg-libx11  # [linux]
    - xorg-libsm   # [linux]

test:
  commands:
    - test -f ${PREFIX}/lib/libwx_baseu-{{ major_minor_version }}${SHLIB_EXT}  # [linux]
    # Not sure why OSX is adding these extra modifiers to SHLIB
    # This is the reason why we aren't including the OSX package in conda-forge just yet.
    # - test -f ${PREFIX}/lib/libwx_baseu-{{ version }}.0.0${SHLIB_EXT}          # [osx]
    - test -f ${PREFIX}/include/wx-{{ major_minor_version }}/wx/wx.h           # [unix]
    - wx-config --prefix  # [unix]
    - wxrc --help  # [unix]
    - where wxrc   # [win]
    - if not exist %LIBRARY_BIN%\\wxrc.exe exit 1  # [win]
    # They keep changing the name of the dll, but I guess that is ok...
    - if not exist %LIBRARY_BIN%\\wxmsw331u_core_vc_x64.dll exit 1  # [win]

about:
  home: https://www.wxwidgets.org/
  license: LicenseRef-wxWindows
  license_family: LGPL
  license_file:
    - docs/licence.txt
    - docs/lgpl.txt
    - docs/gpl.txt
  summary: Cross-Platform GUI Library

  description: |
    wxWidgets is a C++ library that lets developers create applications for
    Windows, macOS, Linux and other platforms with a single code base. It has
    popular language bindings for Python, Perl, Ruby and many other languages,
    and unlike other cross-platform toolkits, wxWidgets gives applications a
    truly native look and feel because it uses the platform's native API rather
    than emulating the GUI. It's also extensive, free, open-source and mature.
  doc_url: https://docs.wxwidgets.org/
  dev_url: https://github.com/wxWidgets/wxWidgets/

extra:
  recipe-maintainers:
    - ryanvolz
    - hmaarrfk
    - pauldmccarthy
